2. mkdir letters
   mkdir reports
   mkdir assignments

3. move ~/letters

4. mkdir frinedly
   mkdir formal

5. cd ~/reports

6. mkdir business personal school

7. mkdir -p ~/assignment/UNIX

8. mkdir -p ~/assignments/UNIX/Projects ~/assignments/UNIX/HWs

9. cd ..

10. 				Student

	letters			reports			assignments
	   
  frinemdly   formal	  personal business school     	    UNIX

						       HWs 	Projects
